#!/bin/sh

usage () {
  cat <<EOF
Update repo with files from EarlyPrint repos

Usage:
$0 [--all | --help]

OPTIONS:
  -a, --all       update all files including existing ones
  -d, --download  download files instead of using submodules
  -h, --help      show this message

Note: By default this script uses the earlyprint repos included
as submodules. These are quite huge and take a while to init and
update. To avoid this, the files can also be downloaded directly
from the bitbucket repo using the --download switch.

EOF
}

# options parsing inspired by
# https://medium.com/@Drew_Stokes/bash-argument-parsing-54f3b81a6a8f

ALL=""
PARAMS=""
DOWNLOAD=""
DELAY=1

while (( "$#" )); do
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    -d|--download)
      DOWNLOAD=yes
      shift
      ;;
    -a|--all)
      ALL=yes
      shift
      ;;
    -v|--verbose)
      VERBOSE=yes
      shift
      ;;
    -*|--*=) # unsupported flags
      echo "Error: Unsupported flag $1" >&2
      exit 1
      ;;
    *) # preserve positional arguments
      PARAMS="$PARAMS $1"
      shift
      ;;
  esac
done

# set positional arguments in their proper place
eval set -- "$PARAMS"

REPO_PATH=earlyprint

# directory with original downloads
TARGET_DIR=./xml
if ! [ -d $TARGET_DIR ]; then
  mkdir -p $TARGET_DIR
fi

v=""
if [ -n "$VERBOSE" ]; then
  v="-v"
fi

git checkout main

# if we are not downloading we initialize and update the submodules before
# copying
if [ -z "$DOWNLOAD" ]; then
  git submodule init
  git submodule update
  for d in $REPO_PATH/*; do
    cd $d
    pwd
    git submodule init
    git submodule update
    cd -
  done
fi

for id in $(cat ids.txt); do
  dir=$(echo $id | cut -c 1-3)
  file="$TARGET_DIR/$id.xml"

  [ -z $VERBOSE ] && echo "$id"
  if ! [[ -f $file ]] || [[ -n "$ALL" ]]; then
    if [ -z "$DOWNLOAD" ]; then
      source=$(ls $REPO_PATH/{eccotcp,eebotcp}/texts/$dir/$id.xml 2>/dev/null)
      cp $v $source $file
    else
      url="https://bitbucket.org/eads004/$dir/raw/master/$id.xml"
      curl -o $file $url
      sleep $DELAY
    fi
  else
    [ -z $VERBOSE ] || echo "$id.xml exists. Skipping."
  fi
done
